FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY envoy_to_mqtt_json.py ./

RUN mkdir -p data
VOLUME ["/app/data"]

ENV PYTHONUNBUFFERED=1

CMD ["python3", "envoy_to_mqtt_json.py"]
